[program:nginx-webui]

#command=java -Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=5006 -Xms2g -Xmx2g -jar art.jar --spring.profiles.active=dev --server.port=8280        ;如果有多条命令，可以写入shell脚本再在这里调用
#command=/opt/java/jdk1.8.0_131/bin/java  -Xms128m -Xmx4g -jar imapi2.war  --spring.profiles.active=test --server.port=9013         ;如果有多条命令，可以写入shell脚本再在这里调用
#command=/opt/java/jdk8u362-b09-jre/bin/java  -Xms1g -Xmx4g -jar imapi2.war  --spring.profiles.active=prod --server.port=9013         ;如果有多条命令，可以写入shell脚本再在这里调用
command=/home/ubuntu/java/jdk1.8.0_131/bin/java  -Xms1g -Xmx3g -jar /home/ubuntu/nginx-webui/nginxWebUI.jar --project.home=/home/ubuntu/nginx-webui --server.port=6030         ;如果有多条命令，可以写入shell脚本再在这里调用

directory=/home/ubuntu/nginx-webui        ;执行命令是切换到的目录

user=root ;执行命令所用的linux用户身份

autorestart=true	;是否自动重启

autostart=true ;启动supervisor时是否自行启动该程序

redirect_stderr=true	;如果为true则将stderr发送到stdout相应的log文件中去

stdout_logfile=/home/ubuntu/nginx-webui/stdout.log	;制定stdout的输出文件

stdout_logfile_maxbytes=50MB	;限定logfile的大小， 默认为50M


stdout_logfile_backups=5 ;保存logfile的最大数目，如果操作这个数目则对最早的logfile进行覆盖，默认为10
