wrapperVersion=3.3.4
distributionType=only-script
# 阿里云
#distributionUrl=https://mirrors.aliyun.com/apache/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.zip
# 腾讯云
#distributionUrl=https://mirrors.cloud.tencent.com/apache/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.zip
# 华为云
distributionUrl=https://repo.huaweicloud.com/apache/maven/maven-3/3.9.16/binaries/apache-maven-3.9.16-bin.zip