http {

    #此处省略其他配置

    server {
            listen 443 ssl http2;
            server_name 域名或者服务器ip;

            ssl_certificate      /root/cert/server.crt;
            ssl_certificate_key  /root/cert/private.key;

            location / {
                      proxy_pass https://api.openai.com;
                      proxy_set_header Host api.openai.com;
                      proxy_set_header X-Real-IP $remote_addr;
            }

    }

}
