version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '180:80'
      - '181:81'
      - '1443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt